---
- name: ensure mysql packages are installed
  action: apt pkg=$item
  with_items:
      - mysql-server
      - python-mysqldb # Required for ansible mysql module to work, see: http://ansible.cc/docs/modules.html#mysql-user

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password=$mysql_password

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: only allow mysql traffic from the host itself
  mysql_user: name=root host=$item password=$root_db_password
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=$item state=absent
  with_items:
    - localhost
    - $inventory_hostname

- name: Create database
  action: mysql_db db=ghost_production state=present

